HEADERS += \
    common/mkp/mod_ext.h \
    common/avstream.h \
    common/faac.h \
    common/faaccfg.h \
    common/gpio_i2c.h \
    common/hi_comm_adec.h \
    common/hi_comm_aenc.h \
    common/hi_comm_ai.h \
    common/hi_comm_aio.h \
    common/hi_comm_ao.h \
    common/hi_comm_hdmi.h \
    common/hi_comm_ive.h \
    common/hi_comm_pciv.h \
    common/hi_comm_rc.h \
    common/hi_comm_region.h \
    common/hi_comm_sys.h \
    common/hi_comm_vb.h \
    common/hi_comm_vda.h \
    common/hi_comm_vdec.h \
    common/hi_comm_venc.h \
    common/hi_comm_vi.h \
    common/hi_comm_video.h \
    common/hi_comm_vo.h \
    common/hi_comm_vpss.h \
    common/hi_common.h \
    common/hi_debug.h \
    common/hi_defines.h \
    common/hi_errno.h \
    common/hi_faac.h \
    common/hi_math.h \
    common/hi_tde_api.h \
    common/hi_tde_errcode.h \
    common/hi_tde_type.h \
    common/hi_type.h \
    common/HI264RTPPACK.h \
    common/hifb.h \
    common/list.h \
    common/loadbmp.h \
    common/mpi_adec.h \
    common/mpi_aenc.h \
    common/mpi_ai.h \
    common/mpi_ao.h \
    common/mpi_hdmi.h \
    common/mpi_ive.h \
    common/mpi_pciv.h \
    common/mpi_region.h \
    common/mpi_sys.h \
    common/mpi_vb.h \
    common/mpi_vda.h \
    common/mpi_vdec.h \
    common/mpi_venc.h \
    common/mpi_vi.h \
    common/mpi_vo.h \
    common/mpi_vpss.h \
    common/sample_comm.h \
    common/samplerate.h \
    common/tlv320aic31.h \
    common/tw2865.h \
    common/tw2960.h \
    src/fbsetting.h \
    src/hi_ascii_8_12.h \
    src/hi_ascii_8_16.h \
    src/hi_ascii_20_24.h \
    src/osdtime.h \
    common/videobuf.h \
    common/zini.h

SOURCES += \
    common/hi_faac.c \
    common/HI264RTPPACK.c \
    common/loadbmp.c \
    common/sample_comm_audio.c \
    common/sample_comm_sys.c \
    common/sample_comm_vda.c \
    common/sample_comm_vdec.c \
    common/sample_comm_venc.c \
    common/sample_comm_vi.c \
    common/sample_comm_vo.c \
    common/sample_comm_vpss.c \
    src/venc.cpp \
    src/fbsetting.c \
    src/osdtime.c \
    common/videobuf.c \
    common/zini.c
